export type IDeclaration = {
  id: number;
  awb: string;
  requiresDeclaration: boolean;
  editable?: boolean;
  user: { id: number; name: string };
  trackCode: string;
  globalTrackCode: string | null;
  status: { id: number; name: string };
  paid: boolean;
  approved: boolean;
  returned: boolean;
  isWanted: boolean;
  wantedDescription: string;
  flight: { id: number; name: string } | null;
  box: { id: number; name: string } | null;
  branch: { id: number; name: string } | null;
  voen: string | null;
  weight: number | null;
  price: number | null;
  currency: string | null;
  deliveryPrice: number | null;
  quantity: number;
  type: "liquid" | "other";
  isCommercial: boolean;
  canAccommodate: boolean;
  planCategory: { id: number; name: string };
  shop: string;
  productType: { id: number; name: string };
  parcel: { id: string } | null;
  basket: { id: string; name: string } | null;
  deliveryPoint: { id: number; name: string } | null;
  wardrobeNumber: string;
  document: string | null;
  read: boolean;
  file: string | null;
  height: number | null;
  width: number | null;
  depth: number | null;
  description: string | null;
  createdAt: string;
  deliveredAt: string;
  countryId: number;
  causerId?: number;
  isYourBranch?: boolean;
  locationName: string;
  locationId: number;
  customs: number;
  handoverTaskId: string | null;
  partnerName: string;
  partnerId: number | null;
};

export type IDeclarationPersistence = {
  id: number;
  awb: string;
  user_id: number;
  user_name: string;
  is_commercial: number;
  requires_declaration: boolean;
  global_track_code: string | null;
  state_id: number;
  state_name: string;
  weight: string | null;
  can_accommodate: boolean;
  price: string | null;
  currency: string | null;
  delivery_price: string | null;
  quantity: number;
  type: number;
  coupon_id: number;
  shop_name: string;
  voen: string | null;
  product_type_id: number;
  product_type_name: string;
  tariff_category_id: number;
  tariff_category_name: string;
  branch_id: number | null;
  branch_name: string | null;
  descr: string | null;
  causer_id: number;
  causer_name: string;
  box?: string;
  basket_id?: string;
  basket_name?: string;
  container_id?: number | null;
  container_name?: string | null;
  track_code: string;
  height: string | null;
  width: string | null;
  depth: string | null;
  is_new: number;
  document_file: string | null;
  payed: number;
  customs: number;
  flight_name: string | null;
  flight_id: number | null;
  wardrobe_number: string;
  created_at: string;
  is_your_branch: boolean;
  location_id: number | null;
  location_name: string | null;
  return: number;
  is_wanted: number;
  wanted_description: string | null;
  country_id: number;
  delivery_point_name: string | null;
  delivery_point_id: number | null;
  who_added_bbs: string | null;
  when_added_bbs: string | null;
  editable?: 1 | 0;
  handover_task_id: string | null;
  delivered_at: string;
  partner_name?: string | null;
  partner_id?: number | null;
};
