export type ICustomsStatus = "Initial" | "Sent" | "Declared" | "Boxed" | "Depesh" | string;

export type ICustomsData = {
  created_at: string;
  Regnumber: string;
  raw_data: Record<string, unknown> | null;
};

export type ITrendyolLog = {
  category: string;
  city: string;
  comment: string;
  createdAt: string;
  declarationId: string;
  weight: string;
  zipCode: string;
  phoneNumber: string;
  domesticCargoCompany: string;
  emailAddress: string;
  fullName: string;
  invoice: { invoicePrice: number | string; invoiceUrl: string };
  isDoor: boolean;
  isDeclared: boolean;
  isLiquid: boolean;
  isMicro: boolean;
  name: string;
  parcelId: string;
  pinCode: string;
  products: { sku: string };
  state: string;
  quantity: string | number;
  shippingAddress: string;
  smsCount: number;
  smsDate: string | null;
  trendyolDeliveryNumber: string;
  type: string;
  unitPrice: string;
  volume: number;
  warehouseId: string;
  uid: string;
  customsStatus: ICustomsStatus;
  barcode: string;
};

export type IDeclaration = {
  id: number;
  awb: string;
  requiresDeclaration: boolean;
  editable?: boolean;
  user: { id: number; name: string };
  trackCode: string;
  globalTrackCode: string | null;
  status: { id: number; name: string };
  paid: boolean;
  approved: boolean;
  returned: boolean;
  isWanted: boolean;
  wantedDescription: string;
  flight: { id: number; name: string } | null;
  box: { id: number; name: string } | null;
  lastBox: { id: number; name: string } | null;
  branch: { id: number; name: string } | null;
  voen: string | null;
  weight: number | null;
  price: number | null;
  currency: string | null;
  deliveryPrice: number | null;
  quantity: number;
  couponId: number;
  type: "liquid" | "other";
  isCommercial: boolean;
  canAccommodate: boolean;
  planCategory: { id: number; name: string };
  shop: string;
  productType: { id: number; name: string };
  parcel: { id: string } | null;
  parcelSorting?: { id: number | null; state_name: string | null; created_at: string | null };
  basket: { id: string; name: string } | null;
  deliveryPoint: { id: number; name: string } | null;
  wardrobeNumber: string;
  document: string | null;
  read: boolean;
  file: string | null;
  height: number | null;
  width: number | null;
  depth: number | null;
  description: string | null;
  createdAt: string;
  deliveredAt: string;
  countryId: number;
  causerId?: number;
  isYourBranch?: boolean;
  locationName: string;
  locationId: number;
  customs: number;
  customsData?: ICustomsData | null;
  trendyol?: number;
  trendyolLogs?: ITrendyolLog | null;
  bbs: { user: string | null; date: string | null };
  handoverTaskId: string | null;
  partnerName: string;
  partnerId: number | null;
};

export type IDeclarationPersistence = {
  id: number;
  awb: string;
  user_id: number;
  user_name: string;
  is_commercial: number;
  requires_declaration: boolean;
  global_track_code: string | null;
  state_id: number;
  state_name: string;
  weight: string | null;
  can_accommodate: boolean;
  price: string | null;
  currency: string | null;
  delivery_price: string | null;
  quantity: number;
  type: number;
  coupon_id: number;
  shop_name: string;
  voen: string | null;
  product_type_id: number;
  product_type_name: string;
  tariff_category_id: number;
  tariff_category_name: string;
  branch_id: number | null;
  branch_name: string | null;
  descr: string | null;
  causer_id: number;
  causer_name: string;
  box?: string;
  basket_id?: string;
  basket_name?: string;
  container_id?: number | null;
  container_name?: string | null;
  container_id_tmp?: number | null;
  container_name_tmp?: string | null;
  parcel_sorting_id?: number | null;
  parcel_sorting_state_name?: string | null;
  parcel_sorting_created_at?: string | null;
  track_code: string;
  height: string | null;
  width: string | null;
  depth: string | null;
  is_new: number;
  document_file: string | null;
  payed: number;
  customs: number;
  flight_name: string | null;
  flight_id: number | null;
  wardrobe_number: string;
  created_at: string;
  is_your_branch: boolean;
  location_id: number | null;
  location_name: string | null;
  return: number;
  is_wanted: number;
  wanted_description: string | null;
  country_id: number;
  delivery_point_name: string | null;
  delivery_point_id: number | null;
  who_added_bbs: string | null;
  when_added_bbs: string | null;
  editable?: 1 | 0;
  handover_task_id: string | null;
  delivered_at: string;
  partner_name?: string | null;
  partner_id?: number | null;
  trendyol?: number;
  customs_data?: ICustomsData | null;
  trendyol_logs?: {
    category: string;
    city: string;
    comment: string;
    created_at: string;
    declaration_id: string;
    domestic_cargo_company: string;
    email_address: string;
    full_name: string;
    customs_status: ICustomsStatus;
    invoice: { invoice_price: number | string; invoice_url: string };
    weight: string;
    zip_code: string;
    phone_number: string;
    is_door: number;
    is_declared: number;
    is_liquid: number;
    is_micro: string | number;
    name: string;
    parcel_id: string;
    pin_code: string;
    products: { sku: string };
    state: string;
    quantity: string | number;
    shipping_address: string;
    sms_count: number;
    sms_date: string | null;
    trendyol_delivery_number: string;
    type: string;
    unit_price: string;
    volume: number;
    warehouse_id: string;
    uid: string[] | null;
    barcode: string;
  };
};
