export type IPartnerDeclaration = {
  id: number;
  user: { id: number; name: string };
  partner: { id: number; name: string };
  trackCode: string;
  globalTrackCode: string | null;
  status: { id: number; name: string };
  flight: { id: number; name: string } | null;
  box: { id: number; name: string } | null;
  lastBox: { id: number; name: string } | null;
  branch: { id: number; name: string } | null;
  weight: number | null;
  price: number | null;
  deliveryPrice: number | null;
  quantity: number;
  type: 'liquid' | 'other';
  planCategory: { id: number; name: string } | null;
  shop: string;
  productType: { id: number; name: string } | null;
  parcel: { id: string } | null;
  basket: { id: string; name: string } | null;
  voen: string | null;
  wardrobeNumber: string;
  editedBy: { id: number; name: string } | null;
  document: string | null;
  file: string | null;
  read: boolean;
  paid: boolean;
  approved: boolean;
  returned: boolean;
  height: number | null;
  width: number | null;
  depth: number | null;
  description: string | null;
  countryId: number;
  customs: number;
  createdAt: string;
};

export type IPartnerDeclarationPersistence = {
  id: number;
  user_id: number;
  user_name: string;
  partner_id: number | null;
  partner_name: string | null;
  track_code: string;
  global_track_code: string | null;
  state_id: number;
  state_name: string;
  flight_id: number | null;
  flight_name: string | null;
  weight: string | null;
  price: string | null;
  delivery_price: string | null;
  quantity: number;
  type: number;
  shop_name: string;
  voen: string | null;
  product_type_id: number | null;
  product_type_name: string | null;
  tariff_category_id: number | null;
  tariff_category_name: string | null;
  branch_id: number | null;
  branch_name: string | null;
  descr: string | null;
  causer_id: number | null;
  causer_name: string | null;
  box?: string;
  basket_id?: string;
  basket_name?: string;
  container_id?: number | null;
  container_name?: string | null;
  container_id_tmp?: number | null;
  container_name_tmp?: string | null;
  height: string | null;
  width: string | null;
  depth: string | null;
  is_new: number;
  document_file: string | null;
  payed: number;
  customs: number;
  wardrobe_number: string;
  created_at: string;
  return: number;
  country_id: number;
};
