export type IUnknownDeclaration = {
  id: number;
  globalTrackCode: string;
  trackCode: string;
  status: { id: number; name: string };
  user: { id: number; name: string } | null;
  weight: number | null;
  price: number | null;
  currency: string | null;
  deliveryPrice: number | null;
  height: number | null;
  width: number | null;
  depth: number | null;
  voen: string | null;
  shop: string;
  quantity: number;
  type: 'liquid' | 'other';
  description: string;
  file: string | null;
  paid: boolean;
  approved: boolean;
  returned: boolean;
  read: boolean;
  countryId: number | null;
  wardrobeNumber: string | null;
  productType: { id: number; name: string } | null;
  planCategory: { id: number; name: string } | null;
  parcel: { id: string } | null;
  basket: { id: string; name: string } | null;
  box: { id: number; name: string } | null;
  lastBox: { id: number; name: string } | null;
  branch: { id: number; name: string } | null;
  flight: { id: number; name: string } | null;
  deliveryPoint: { id: number; name: string } | null;
  partnerName: string;
  partnerId: number | null;
  handoverTaskId: string | null;
  createdAt: string;
  deliveredAt: string | null;
};

export type IUnknownDeclarationPersistence = {
  id: number;
  global_track_code: string;
  track_code: string;
  state_id: number;
  state_name: string;
  user_id: number | null;
  user_name: string | null;
  weight: string | null;
  price: string | null;
  created_at: string;
  currency?: string | null;
  delivery_price?: string | null;
  height?: string | null;
  width?: string | null;
  depth?: string | null;
  voen?: string | null;
  shop_name?: string;
  quantity?: number;
  type?: number;
  descr?: string | null;
  document_file?: string | null;
  payed?: number;
  customs?: number;
  return?: number;
  is_new?: number;
  country_id?: number | null;
  wardrobe_number?: string | null;
  product_type_id?: number | null;
  product_type_name?: string | null;
  tariff_category_id?: number | null;
  tariff_category_name?: string | null;
  box?: string | null;
  basket_id?: string | null;
  basket_name?: string | null;
  container_id?: number | null;
  container_name?: string | null;
  container_id_tmp?: number | null;
  container_name_tmp?: string | null;
  branch_id?: number | null;
  branch_name?: string | null;
  flight_name?: string | null;
  delivery_point_id?: number | null;
  delivery_point_name?: string | null;
  partner_name?: string | null;
  partner_id?: number | null;
  handover_task_id?: string | null;
  delivered_at?: string | null;
};
