export const declarationQueryKeys = {
  id: "id",
  userId: "user_id",
  userName: "user_name",
  trackCode: "track_code",
  globalTrackCode: "global_track_code",
  statusId: "state_id",
  countryId: "country_id",
  flightName: "flight_name",
  weight: "weight",
  price: "price",
  deliveryPrice: "delivery_price",
  quantity: "quantity",
  type: "type",
  planCategoryId: "tariff_category_id",
  shopName: "shop_name",
  productTypeId: "product_type_id",
  branchId: "branch_id",
  parcelId: "box",
  boxId: "container_id",
  paid: "payed",
  approved: "customs",
  returned: "return",
  createdAt: "created_at",
};
