export type IOrder = {
  id: number;
  trackCode: string;
  user: { id: number; name: string };
  status: { id: number; name: string };
  paid: boolean;
  returned: boolean;
  couponId: number;
  product: {
    url: string;
    size: string;
    color: string;
    price: number;
    internalShippingPrice: number;
    shop: string;
    quantity: number;
    type: { id: number; name: string } | null;
  };
  executor: { id: number; name: string } | null;
  declaration: { id: number; trackCode: string } | null;
  debts: { productPrice: number; internalShippingPrice: number };
  read: boolean;
  isUrgent: boolean;
  rejectionReason: string;
  countryId: number;
  description: string;
  expectedAt: string | null;
  updatedAt: string | null;
  createdAt: string;
};
